services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: scriptural
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
